import i18next from "i18next";

export const getWeddingThemes = () => [
  { value: "classic", label: i18next.t("weddingThemes.classic") },
  { value: "rustic", label: i18next.t("weddingThemes.rustic") },
  { value: "vintage", label: i18next.t("weddingThemes.vintage") },
  { value: "modern", label: i18next.t("weddingThemes.modern") },
  { value: "bohemian", label: i18next.t("weddingThemes.bohemian") },
  { value: "garden", label: i18next.t("weddingThemes.garden") },
  { value: "beach", label: i18next.t("weddingThemes.beach") },
  { value: "industrial", label: i18next.t("weddingThemes.industrial") },
  { value: "romantic", label: i18next.t("weddingThemes.romantic") },
  { value: "tropical", label: i18next.t("weddingThemes.tropical") },
  { value: "winter", label: i18next.t("weddingThemes.winter") },
  { value: "spring", label: i18next.t("weddingThemes.spring") },
  { value: "summer", label: i18next.t("weddingThemes.summer") },
  { value: "autumn", label: i18next.t("weddingThemes.autumn") },
  { value: "mediterranean", label: i18next.t("weddingThemes.mediterranean") },
  { value: "asian", label: i18next.t("weddingThemes.asian") },
  { value: "french", label: i18next.t("weddingThemes.french") },
  { value: "tuscany", label: i18next.t("weddingThemes.tuscany") },
  { value: "nordic", label: i18next.t("weddingThemes.nordic") },
  { value: "art-deco", label: i18next.t("weddingThemes.artDeco") },
  { value: "barn", label: i18next.t("weddingThemes.barn") },
  { value: "winery", label: i18next.t("weddingThemes.winery") },
  { value: "castle", label: i18next.t("weddingThemes.castle") },
  { value: "destination", label: i18next.t("weddingThemes.destination") },
  { value: "cultural", label: i18next.t("weddingThemes.cultural") },
  { value: "eclectic", label: i18next.t("weddingThemes.eclectic") },
  { value: "luxury", label: i18next.t("weddingThemes.luxury") },
  { value: "intimate", label: i18next.t("weddingThemes.intimate") },
  { value: "grand", label: i18next.t("weddingThemes.grand") },
  { value: "casual", label: i18next.t("weddingThemes.casual") },
];

